base_score: 0.5
booster: gbtree
colsample_bylevel: 1
colsample_bynode: 1
colsample_bytree: 1
gamma: 0
gpu_id: -1
importance_type: gain
interaction_constraints: ''
learning_rate: 0.300000012
max_delta_step: 0
max_depth: 6
min_child_weight: 1
missing: .nan
monotone_constraints: ()
n_estimators: 10000
n_jobs: 0
num_parallel_tree: 1
objective: reg:squarederror
random_state: 1121218
reg_alpha: 0
reg_lambda: 1
scale_pos_weight: 1
subsample: 1
tree_method: exact
validate_parameters: 1
verbosity: null
